import jsPDF from "jspdf";

export const downloadReport = ({
  candidate,
  resumeText,
  atsScore,
  aiAnalysis,
}) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("ResumeIQ AI Pro", 20, 18);

  doc.setFontSize(11);
  doc.text("AI Powered Resume Analysis Report", 20, 25);

  // Reset
  doc.setTextColor(0, 0, 0);

  let y = 45;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Candidate Details", 20, y);

  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(`Name : ${candidate.name}`, 20, y);
  y += 8;

  doc.text(`Email : ${candidate.email}`, 20, y);
  y += 8;

  doc.text(`Phone : ${candidate.phone}`, 20, y);
  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("Resume Statistics", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");

  doc.text(`ATS Score : ${atsScore}%`, 20, y);
  y += 8;

  doc.text(
    `Words : ${
      resumeText.trim()
        ? resumeText.trim().split(/\s+/).length
        : 0
    }`,
    20,
    y
  );

  y += 8;

  doc.text(
    `Characters : ${resumeText.length}`,
    20,
    y
  );

  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("AI Analysis", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(
    aiAnalysis || "No AI Analysis Available",
    170
  );

  doc.text(lines, 20, y);

  y += lines.length * 7 + 10;

  doc.setFont("helvetica", "bold");
  doc.text("Generated On", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleString(), 20, y);

  // Footer
  doc.setDrawColor(200);
  doc.line(20, 285, 190, 285);

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by ResumeIQ AI Pro © 2025",
    20,
    292
  );

  doc.save("ResumeIQ_AI_Report.pdf");
};